[package]
name = "vfsd"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"

[lib]
path = "src/lib.rs"

[[bin]]
name = "vfsd"
path = "src/main.rs"

[features]
default = ["idl-capnp"]
idl-capnp = ["nexus-idl-runtime/capnp", "dep:capnp"]
os-lite = []

[dependencies]
capnp = { version = "0.19", optional = true }
log = "0.4"
parking_lot = "0.12"
thiserror = "1.0"

nexus-idl-runtime = { path = "../../../userspace/nexus-idl-runtime" }
nexus-ipc = { path = "../../../userspace/nexus-ipc", default-features = false, features = ["os-lite"] }
nexus-packagefs = { path = "../../../userspace/nexus-packagefs" }
