[package]
name = "vfsd"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"

[lib]
path = "src/lib.rs"

[[bin]]
name = "vfsd"
path = "src/main.rs"

[features]
default = ["idl-capnp"]
idl-capnp = []

[dependencies]
capnp = "0.18"
log = "0.4"
parking_lot = "0.12"
thiserror = "1.0"

nexus-idl-runtime = { path = "../../../userspace/nexus-idl-runtime", features = ["idl-capnp"] }
nexus-ipc = { path = "../../../userspace/nexus-ipc" }
nexus-packagefs = { path = "../../../userspace/nexus-packagefs" }
