[package]
name = "init-lite"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
publish = false

[dependencies]
nexus-abi = { path = "../../libs/nexus-abi" }
nexus-service-entry = { path = "../../libs/nexus-service-entry" }
nexus-log = { path = "../../libs/nexus-log", features = ["sink-userspace"] }
nexus-init = { path = "../../init/nexus-init", features = ["os-payload"], default-features = false }

[build-dependencies]
object = "0.32"
