[allow]
samgrd = ["ipc.core", "time.read"]
bundlemgrd = ["fs.read", "fs.verify", "ipc.core"]
keystored = ["crypto.sign", "crypto.verify", "ipc.core", "rng.entropy", "device.keygen", "policy.delegate"]
execd = ["proc.spawn", "ipc.core", "fs.read"]
"packagefsd" = ["ipc.core", "fs.read"]
"vfsd" = ["ipc.core"]
"nexus-init" = ["proc.spawn", "ipc.core", "fs.read"]
updated = ["crypto.verify", "ipc.core"]
dsoftbusd = ["ipc.core"]
rngd = ["device.mmio.rng", "ipc.core", "policy.delegate"]
"selftest-client" = ["ipc.core", "proc.spawn", "rng.entropy", "device.keygen", "device.pubkey.read"]
"demo.testsvc" = []
