[allow]
samgrd = ["ipc.core", "time.read"]
bundlemgrd = ["fs.read", "fs.verify", "ipc.core"]
keystored = ["crypto.sign", "crypto.verify", "ipc.core"]
execd = ["proc.spawn", "ipc.core", "fs.read"]
"packagefsd" = ["ipc.core", "fs.read"]
"vfsd" = ["ipc.core"]
"nexus-init" = ["proc.spawn", "ipc.core", "fs.read"]
updated = ["crypto.verify", "ipc.core"]
dsoftbusd = ["ipc.core"]
"selftest-client" = ["ipc.core", "proc.spawn"]
"demo.testsvc" = []
