[package]
name = "bundlemgr"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
authors = ["Open Nexus OS Contributors"]

[dependencies]
semver = "1"
thiserror = "1"
capnp = "0.19"
hex = "0.4"
nexus-idl-runtime = { path = "../nexus-idl-runtime" }
