[package]
name = "keystored"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"

[features]
default = ["std", "idl-capnp"]
std = [
    "dep:keystore",
    "dep:nexus-idl-runtime",
    "dep:nexus-ipc",
    "nexus-ipc/std",
    "dep:thiserror"
]
idl-capnp = ["nexus-idl-runtime/capnp", "dep:capnp"]
os-lite = [
    "dep:nexus-service-entry",
    "dep:nexus-abi",
    "dep:nexus-ipc",
    "nexus-ipc/os-lite",
    "nexus-ipc/kernel-ipc",
    "dep:ed25519-dalek",
    "dep:statefs",
    "statefs/ipc-client",
]

[dependencies]
keystore = { path = "../../../userspace/keystore", optional = true }
nexus-idl-runtime = { path = "../../../userspace/nexus-idl-runtime", optional = true }
capnp = { version = "0.24", optional = true }
nexus-ipc = { path = "../../../userspace/nexus-ipc", optional = true, default-features = false }
thiserror = { version = "1", optional = true }
nexus-service-entry = { path = "../../libs/nexus-service-entry", optional = true }
nexus-abi = { path = "../../libs/nexus-abi", optional = true }
ed25519-dalek = { version = "2", default-features = false, features = ["alloc"], optional = true }
statefs = { path = "../../../userspace/statefs", optional = true, default-features = false }

[[bin]]
name = "keystored"
path = "src/main.rs"
