[package]
name = "neuron-boot"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"

[dependencies]
neuron = { path = "../neuron", features = ["bringup_identity"] }

[features]
trap_ring = ["neuron/trap_ring"]
trap_symbols = ["neuron/trap_symbols"]
debug_uart = ["neuron/debug_uart"]
ipc_trace_ring = ["neuron/ipc_trace_ring"]

[[bin]]
name = "neuron-boot"
path = "src/main.rs"
test = false
bench = false
doctest = false
