[package]
name = "samgrd"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"

[features]
default = ["std", "idl-capnp"]
std = [
    "dep:nexus-idl-runtime",
    "dep:samgr",
    "dep:capnp",
    "dep:nexus-ipc",
    "nexus-ipc/std",
]
idl-capnp = ["nexus-idl-runtime/capnp", "dep:capnp"]
os-lite = [
    "dep:nexus-service-entry",
    "dep:nexus-abi",
    "dep:nexus-ipc",
    "dep:nexus-log",
    "nexus-ipc/os-lite",
    "nexus-ipc/kernel-ipc",
]

[dependencies]
nexus-idl-runtime = { path = "../../../userspace/nexus-idl-runtime", optional = true }
samgr = { path = "../../../userspace/samgr", optional = true }
capnp = { version = "0.24", optional = true }
nexus-ipc = { path = "../../../userspace/nexus-ipc", optional = true, default-features = false }
nexus-service-entry = { path = "../../libs/nexus-service-entry", optional = true }
nexus-abi = { path = "../../libs/nexus-abi", optional = true }
nexus-log = { path = "../../libs/nexus-log", default-features = false, features = ["sink-logd"], optional = true }

[[bin]]
name = "samgrd"
path = "src/main.rs"
