[package]
name = "dsoftbusd"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"

[features]
default = ["std"]
std = []
os-lite = []

[dependencies]

[target.'cfg(not(target_os = "none"))'.dependencies]
dsoftbus = { path = "../../../userspace/dsoftbus" }

[target.'cfg(all(target_os = "none", target_arch = "riscv64"))'.dependencies]
nexus-service-entry = { path = "../../libs/nexus-service-entry" }
nexus-abi = { path = "../../libs/nexus-abi" }
nexus-ipc = { path = "../../../userspace/nexus-ipc", default-features = false, features = ["os-lite", "kernel-ipc"] }
nexus-log = { path = "../../libs/nexus-log", default-features = false, features = ["sink-logd"] }
nexus-noise-xk = { path = "../../libs/nexus-noise-xk" }
nexus-discovery-packet = { path = "../../libs/nexus-discovery-packet" }
nexus-peer-lru = { path = "../../libs/nexus-peer-lru" }
