[package]
name = "nexus-packagefs"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"

[features]
default = ["idl-capnp"]
idl-capnp = ["nexus-idl-runtime/capnp", "dep:capnp"]

[dependencies]
capnp = { version = "0.24", optional = true }
nexus-idl-runtime = { path = "../nexus-idl-runtime" }
nexus-ipc = { path = "../nexus-ipc" }
thiserror = "1"
