[package]
name = "rngd"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"

[features]
default = ["std"]
std = ["dep:thiserror"]
os-lite = [
    "dep:nexus-service-entry",
    "dep:nexus-abi",
    "dep:nexus-ipc",
    "nexus-ipc/os-lite",
    "nexus-ipc/kernel-ipc",
    "dep:rng-virtio",
    "rng-virtio/os-lite",
]

[dependencies]
thiserror = { version = "1", optional = true }
nexus-service-entry = { path = "../../libs/nexus-service-entry", optional = true }
nexus-abi = { path = "../../libs/nexus-abi", optional = true }
nexus-ipc = { path = "../../../userspace/nexus-ipc", optional = true, default-features = false }
rng-virtio = { path = "../../drivers/rng/virtio-rng", optional = true, default-features = false }

[[bin]]
name = "rngd"
path = "src/main.rs"
