[package]
name = "bundlemgrd"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"

[features]
default = ["std", "idl-capnp"]
std = [
    "dep:bundlemgr",
    "dep:nexus-idl-runtime",
    "dep:capnp",
    "dep:nexus-ipc",
    "nexus-ipc/std",
    "dep:keystored",
    "dep:memchr",
    "dep:sha2",
    "dep:hex",
    "dep:nexus-packagefs",
]
idl-capnp = ["nexus-idl-runtime/capnp", "dep:capnp"]
os-lite = [
    "dep:nexus-service-entry",
    "dep:nexus-abi",
    "dep:nexus-ipc",
    "dep:nexus-log",
    "nexus-ipc/os-lite",
    "nexus-ipc/kernel-ipc",
]

[dependencies]
bundlemgr = { path = "../../../userspace/bundlemgr", optional = true }
nexus-idl-runtime = { path = "../../../userspace/nexus-idl-runtime", optional = true }
capnp = { version = "0.19", optional = true }
nexus-ipc = { path = "../../../userspace/nexus-ipc", optional = true, default-features = false }
keystored = { path = "../keystored", features = ["idl-capnp"], optional = true }
memchr = { version = "2", optional = true }
sha2 = { version = "0.10", optional = true }
hex = { version = "0.4", optional = true }
nexus-packagefs = { path = "../../../userspace/nexus-packagefs", optional = true }
nexus-service-entry = { path = "../../libs/nexus-service-entry", optional = true }
nexus-abi = { path = "../../libs/nexus-abi", optional = true }
nexus-log = { path = "../../libs/nexus-log", default-features = false, features = ["sink-logd"], optional = true }

[lib]
path = "src/lib.rs"
doctest = false

[[bin]]
name = "bundlemgrd"
path = "src/main.rs"
