[package]
name = "packagefsd"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"

[features]
default = ["idl-capnp"]
idl-capnp = ["nexus-idl-runtime/capnp", "dep:capnp"]

[dependencies]
capnp = { version = "0.19", optional = true }
nexus-idl-runtime = { path = "../../../userspace/nexus-idl-runtime" }
nexus-ipc = { path = "../../../userspace/nexus-ipc" }
parking_lot = "0.12"
thiserror = "1"
log = "0.4"

[[bin]]
name = "packagefsd"
path = "src/main.rs"
