[package]
name = "packagefsd"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"

[features]
default = ["std", "idl-capnp"]
std = [
    "dep:nexus-idl-runtime",
    "dep:nexus-ipc",
    "nexus-ipc/std",
    "dep:capnp",
    "dep:parking_lot",
    "dep:thiserror",
    "dep:log",
]
idl-capnp = ["nexus-idl-runtime/capnp", "dep:capnp"]
os-lite = [
    "dep:nexus-service-entry",
    "dep:nexus-abi",
    "dep:nexus-ipc",
    "nexus-ipc/os-lite",
    "nexus-ipc/kernel-ipc",
]

[dependencies]
capnp = { version = "0.19", optional = true }
nexus-idl-runtime = { path = "../../../userspace/nexus-idl-runtime", optional = true }
nexus-ipc = { path = "../../../userspace/nexus-ipc", optional = true, default-features = false }
parking_lot = { version = "0.12", optional = true }
thiserror = { version = "1", optional = true }
log = { version = "0.4", optional = true }
nexus-service-entry = { path = "../../libs/nexus-service-entry", optional = true }
nexus-abi = { path = "../../libs/nexus-abi", optional = true }

[[bin]]
name = "packagefsd"
path = "src/main.rs"
