[package]
name = "exec-payloads"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
authors = ["Open Nexus OS Contributors"]

[dependencies]
nexus-abi = { path = "../../source/libs/nexus-abi" }
