[package]
name = "timed"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"

[features]
default = ["std"]
std = []
os-lite = [
    "dep:nexus-service-entry",
    "dep:nexus-abi",
    "dep:nexus-ipc",
    "nexus-ipc/os-lite",
    "nexus-ipc/kernel-ipc",
]

[lib]
path = "src/lib.rs"

[dependencies]
nexus-service-entry = { path = "../../libs/nexus-service-entry", optional = true }
nexus-abi = { path = "../../libs/nexus-abi", optional = true }
nexus-ipc = { path = "../../../userspace/nexus-ipc", optional = true, default-features = false }

[[bin]]
name = "timed"
path = "src/main.rs"
